--- lua-5.3.5/src/Makefile	1578230443.908267000
+++ patches/lua-5.3.5/src/Makefile	1578230443.908267000
@@ -6,14 +6,15 @@
 # Your platform. See PLATS for possible values.
 PLAT= none
 
-CC= gcc -std=gnu99
+CC= clang -std=gnu99
 CFLAGS= -O2 -Wall -Wextra -DLUA_COMPAT_5_2 $(SYSCFLAGS) $(MYCFLAGS)
 LDFLAGS= $(SYSLDFLAGS) $(MYLDFLAGS)
 LIBS= -lm $(SYSLIBS) $(MYLIBS)
 
-AR= ar rcu
-RANLIB= ranlib
+AR= llvm-ar rcu
+RANLIB= llvm-ranlib
 RM= rm -f
+LDID= ldid -S/usr/share/SDKs/x.ent
 
 SYSCFLAGS=
 SYSLDFLAGS=
@@ -29,6 +30,7 @@
 PLATS= aix bsd c89 freebsd generic linux macosx mingw posix solaris
 
 LUA_A=	liblua.a
+LUA_D=	liblua.dylib
 CORE_O=	lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o \
 	lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o \
 	ltm.o lundump.o lvm.o lzio.o
@@ -43,8 +45,9 @@
 LUAC_O=	luac.o
 
 ALL_O= $(BASE_O) $(LUA_O) $(LUAC_O)
-ALL_T= $(LUA_A) $(LUA_T) $(LUAC_T)
+ALL_T= $(LUA_A) $(LUA_D) $(LUA_T) $(LUAC_T)
 ALL_A= $(LUA_A)
+ALL_D= $(LUA_D)
 
 # Targets start here.
 default: $(PLAT)
@@ -55,15 +58,23 @@
 
 a:	$(ALL_A)
 
+dylib:	$(ALL_D)
+
 $(LUA_A): $(BASE_O)
 	$(AR) $@ $(BASE_O)
 	$(RANLIB) $@
 
-$(LUA_T): $(LUA_O) $(LUA_A)
-	$(CC) -o $@ $(LDFLAGS) $(LUA_O) $(LUA_A) $(LIBS)
-
-$(LUAC_T): $(LUAC_O) $(LUA_A)
-	$(CC) -o $@ $(LDFLAGS) $(LUAC_O) $(LUA_A) $(LIBS)
+$(LUA_D):	$(BASE_O)
+	$(CC) -o $@ -dynamiclib -install_name @rpath/$@ $(LDFLAGS) $(BASE_O)
+	$(LDID) $@
+
+$(LUA_T): $(LUA_O) $(LUA_A) $(LUA_D)
+	$(CC) -o $@ $(LDFLAGS) $(LUA_O) $(LUA_D) $(LIBS)
+	$(LDID) $@
+
+$(LUAC_T): $(LUAC_O) $(LUA_A) $(LUA_D)
+	$(CC) -o $@ $(LDFLAGS) $(LUAC_O) $(LUA_D) $(LIBS)
+	$(LDID) $@
 
 clean:
 	$(RM) $(ALL_T) $(ALL_O)
